### ISSUE TITLE
Two questions xD

### ISSUE THREAD

**Issue by Deykii** [ramensoftware/windows-11-start-menu-styling-guide#101]
Firstly, is there any way to make for example Windows11_Metro10 translucent, just like TranslucentStartMenu

Secondly, even if I target these: Windows.UI.Xaml.Controls.Grid#ShowMoreSuggestions, Windows.UI.Xaml.Controls.Grid#SuggestionsParentContainer, Windows.UI.Xaml.Controls.Grid#TopLevelSuggestionsListHeader as Visibility=Collapsed, Recommendation is still there 
![image](https://github.com/user-attachments/assets/6c3a6a2c-15c0-4850-9455-c7de61f561a0)

**Comment by Deykii** [comment]
Okay, I solved problem with Recomendations!

**Comment by bbmaster123** [comment]
Glad to hear!!
Since you already figured out how to find targets, you can skip ahead to the [color] section in the readme. (https://github.com/ramensoftware/windows-11-taskbar-styling-guide?tab=readme-ov-file#colors)
Let me know if you need help after reading that! :)
