### ISSUE TITLE
Question about the width of the start menu

### ISSUE THREAD

**Issue by Hottihotte** [ramensoftware/windows-11-start-menu-styling-guide#106]
![1](https://github.com/user-attachments/assets/64e71c43-f2f6-4d7d-97e0-67db3d96741e)
Is there a way to make the wide empty area narrower when no apps are pinned and it automatically widens when you pin apps, like in Windows 10?

**Comment by bbmaster123** [comment]
Not automatically no. Unfortunately the windows 11 start menu isn't currently user resizable at all, although there is a visual state in there called ResizeEnabled so maybe with another future mod. We can style visual states with the start menu styler mod, but not set them directly.

The best we can do right now is create (I have an older Windows10 minimal somewhere in my vm) a variant, with appslist only, and the menu manually made narrower.
Then you would have to swap between theme variants whenever you need to. not exactly ideal

**Comment by Hottihotte** [comment]
> Not automatically no. Unfortunately the windows 11 start menu isn't currently user resizable at all, although there is a visual state in there called ResizeEnabled so maybe with another future mod. We can style visual states with the start menu styler mod, but not set them directly.
> 
> The best we can do right now is create (I have an older Windows10 minimal somewhere in my vm) a variant, with appslist only, and the menu manually made narrower. Then you would have to swap between theme variants whenever you need to. not exactly ideal

Thanks for the answer.
It works with ExplorerPatcher, but since I'm now focusing on Windhawk and want to leave out the EP entirely, I asked.
The reason is that I don't want to run two tools and the EP is already declared "undesirable" in Defender.

I would be happy if that were possible and changing the design (when you pin apps) wouldn't be a problem.

**Comment by bbmaster123** [comment]
Yea it does work with EP like you say, you could even use windhawk to style the real w10 menu from EP, even on 24h2, just the targets are a bit different. 

I'm personally keeping EP on my main system, I just love the weather widget on the w10 taskbar too much! haha

Agreed, but that likely wont be possible as long as the apps list and pinned list are are 2 separate view modes by default, unlike the windows 10 start menu

**Comment by Hottihotte** [comment]
Looks like I have to use both tools

**Comment by bbmaster123** [comment]
because you have 2 notepads open? if you set not to group, then it wont group, I don't understand the incompatibility? Besides, EP does work with windhawk and the styler mods, just the windows 10 taskbar cant be styled. EP with windows 11 taskbar works fine, win10/win11 start menu works fine, etc

here's a quick example with win10 start and win11 taskbar on 24h2
![image](https://github.com/user-attachments/assets/a327c074-ef56-46a5-8c58-49cb6d9bd132)


Anyway let me know if there's something I can help you with in regards to styling, cheers!

**Comment by Hottihotte** [comment]
> because you have 2 notepads open? if you set not to group, then it wont group, I don't understand the incompatibility? Besides, EP does work with windhawk and the styler mods, just the windows 10 taskbar cant be styled. EP with windows 11 taskbar works fine, win10/win11 start menu works fine, etc
> 
> here's a quick example with win10 start and win11 taskbar on 24h2 ![image](https://private-user-images.githubusercontent.com/92948468/382775750-a327c074-ef56-46a5-8c58-49cb6d9bd132.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3NjU1MjcsIm5iZiI6MTczMDc2NTIyNywicGF0aCI6Ii85Mjk0ODQ2OC8zODI3NzU3NTAtYTMyN2MwNzQtZWY1Ni00NmE1LThjNTgtNDljYjZkOWJkMTMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDAwMDcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4MTEzMTczMDgxMjdjMTViNzgxNGFjZjEyOTVkZGEwMWM2Y2VmM2MwMDI3MTI0ZDU5MDRmODQ1NjE3YTVmMzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mfVyFXA7qHfbfO4fiNJlJHmeSdghO5asyu0wzLxYiic)
> 
> Anyway let me know if there's something I can help you with in regards to styling, cheers!

**Comment by m417z** [comment]
@Hottihotte the mod works with ExplorerPatcher, you just need to make sure to enable the relevant option ("Customize the old taskbar on Windows 11") in the settings.

**Comment by Hottihotte** [comment]
> @Hottihotte the mod works with ExplorerPatcher, you just need to make sure to enable the relevant option ("Customize the old taskbar on Windows 11") in the settings.
Unfortunately it doesn't work or I'm doing something wrong

https://github.com/user-attachments/assets/92bc78f3-786a-4bac-9b19-0ee26202b6e9


https://github.com/user-attachments/assets/516075b5-8352-4d85-8d1f-156bda0449da

The two settings work, but the taskbar style "Windows 10" is no longer supported by EP and with the taskbar style "Windows 10 ExplorerPatcher" the whole thing looks like this, please pay attention to the folders in the taskbar.

https://github.com/user-attachments/assets/4bd15ab4-af8a-43ca-82bd-104add35222d

It is no longer possible to move different files of the same application separately.

**Comment by m417z** [comment]
It's supposed to work, make sure your ExplorerPatcher version is newer than 66.6 and that you enabled the option for the old taskbar in the mod's settings. If it still doesn't work, create a new issue here and attach debug logs:
https://github.com/ramensoftware/windhawk-mods/issues

**Comment by m417z** [comment]
Yes, I worked with the ExplorerPatcher maintainer to add support for some of the mods, see:
https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#windhawk-mods-support

**Comment by Hottihotte** [comment]
> Yes, I worked with the ExplorerPatcher maintainer to add support for some of the mods, see: https://github.com/valinet/ExplorerPatcher/wiki/ExplorerPatcher's-taskbar-implementation#windhawk-mods-support
I have to apologize.
I overlooked in the description of the mod that I have to activate the option "Customize the old taskbar on Windows 11" in the mod's settings
Now it works perfectly
