### ISSUE TITLE
How to Adjust the ExpandedFolderList to fit and not overflow the whole start menu

### ISSUE THREAD

**Issue by Gyanzo-p3pper-derm** [ramensoftware/windows-11-start-menu-styling-guide#117]
![image](https://github.com/user-attachments/assets/5c4e1cb0-2cc3-4fbf-992d-9218873b5c42)

I tried playing with sStartMenu.ExpandedFolderList to get it working but it seems to overflow in TransluscentMenu but works well in Windows11_Metro10 
![image](https://github.com/user-attachments/assets/289d75d2-a59b-4dc9-9f5f-260d95352fa3)

Please how can I adjust it's margin size to match that of the Windows11_Metro10

**Comment by bbmaster123** [comment]
Yea that makes sense, I had to fix that same issue in every built-in theme that has the apps list visible...

try the style code from my theme:

```
Target:
StartMenu.ExpandedFolderList > Grid > Border
Styles:
Margin=-145,0,145,0
Width=312
```

```
Target:
StartMenu.ExpandedFolderList > Grid > Grid

Styles:
Width=350
Margin=-295,0,0,0
```

```
Target:
StartMenu.ExpandedFolderList > Grid > Grid > Microsoft.UI.Xaml.Controls.PipsPager#PinnedListPipsPager

Styles:
Margin=-18,0,0,0
```

adjust values as needed. Let me know if it still doesn't look right! :)

**Comment by Gyanzo-p3pper-derm** [comment]
Thanks It worked
