### ISSUE TITLE
[BUG] The Pinned Apps section doesn't expand after "Remove the Recommended section" configured.

### ISSUE THREAD

**Issue by HumanMus1c** [ramensoftware/windows-11-start-menu-styling-guide#12]
![recording](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/46023154/b0f7e1f9-42c0-467c-841c-02ec5b3913d5)

**Comment by m417z** [comment]
Setting `Height=504` for `StartMenu.PinnedList` should help.

**Comment by HumanMus1c** [comment]
Thank you, sir. May I ask this object belongs to "Resource variables" or "Control styles" ?

**Comment by m417z** [comment]
Control styles

**Comment by HumanMus1c** [comment]
Thanks, it's working.
