### ISSUE TITLE
How to make this transparent

### ISSUE THREAD

**Issue by Deykii** [ramensoftware/windows-11-start-menu-styling-guide#122]
I merged TranslucentStartMenu and Windows11Metro10 and now the only thing that is not that acryllic is that folder window and search menu
![image](https://github.com/user-attachments/assets/141ca0c0-de3d-471f-9ff5-76fc4f4cb259)
![image](https://github.com/user-attachments/assets/4bdb19d9-a75f-44ca-b1b2-86cd1a8ce752)

Example:
![image](https://github.com/user-attachments/assets/929f7285-88a7-445f-aebb-897a6ecb40ee)

**Comment by bbmaster123** [comment]
```
StartMenu.ExpandedFolderList > Border
Background=<color>
```

for search, add searchhost.exe to the inclusion list in the mod's advanced tab at the top. Use UWPspy to find targets that aren't automatically styled using the start menu's targets (some are shared, some are unique)

hope that helps :)

**Comment by Deykii** [comment]
> ```
> StartMenu.ExpandedFolderList > Border
> Background=<color>
> ```
> 
> Use UWPspy to find targets that aren't automatically styled using the start menu's targets (some are shared, some are unique)


Sorry I didn't get it

**Comment by Deykii** [comment]
I did it!
![image](https://github.com/user-attachments/assets/68e27083-ed8a-4a74-ab6d-1fc86b3f9bf0)
But... Yeah... Sorry for that much stupid questions... Is there a way to get rid of border around the folder title?

**Comment by bbmaster123** [comment]
all good! However, please read through the [UWPspy guide](https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md) for finding targets when you have some time, I promise it will be at least a little helpful :)

For the folder title background, the target is:
`Windows.UI.Xaml.Controls.TextBox#ExpandedFolderNameTextBox`

**Comment by Deykii** [comment]
> all good! However, please read through the [UWPspy guide](https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md) for finding targets when you have some time, I promise it will be at least a little helpful :)
> 
> For the folder title background, the target is: `Windows.UI.Xaml.Controls.TextBox#ExpandedFolderNameTextBox`

Yeah, sorry, I just didn't have much time earlier😅
Thank you!!!!!
