### ISSUE TITLE
Cant see selected apps using arrow keys

### ISSUE THREAD

**Issue by AshKxK** [ramensoftware/windows-11-start-menu-styling-guide#123]
As the title says I cant see the selected app when I'm using the arrow keys. Using the Fluesnt2Inspired theme.

Right now Epic Games is supposed to be chosen

![image](https://github.com/user-attachments/assets/4e9d38cc-fb5d-4688-8a6b-2274734827d1)

**Comment by bbmaster123** [comment]
iirc, it was designed to be like that, but its possible I overlooked it. I can always update the theme to restore the outline, but in the meantime, add this style in the mod's settings:

```
Target:
Windows.UI.Xaml.Controls.GridViewItem

Styles: 
FocusVisualMargin=2
FocusVisualPrimaryBrush:=<SolidColorBrush Color="{ThemeResource SystemAccentColor}" Opacity=".85"/>
CornerRadius=8
```

the first style controls how thick the outline is, second style sets the color to your accent color in windows at 85% opacity, and last style gives rounded corners. Let me know if you need any help getting it to look how you want!

cheers :)

**Comment by AshKxK** [comment]
It aint working on arrow keys, only on mouse hover. Hopefully I haven't missed something :))
![image](https://github.com/user-attachments/assets/d4d3b084-fbb2-4aeb-a670-9865ee4e8b0e)

Now Apex Legends is selected(with arrows).
![image](https://github.com/user-attachments/assets/a25c0df6-7546-434c-942b-7db93308e2d7)

It looks like this when I hover my the mouse over it.
![image](https://github.com/user-attachments/assets/0ed84bcc-beb9-46e0-8e24-a6c650439445)

**Comment by bbmaster123** [comment]
No it looks like you've done it correctly, maybe try restarting explorer/startmenuexperiencehost.exe? Have you added any other styles? If so, can you share your whole style code?

If your accent color is the standard windows blue, you should be seeing a blue outline with the arrow keys and when tabbing
let me know, we'll figure it out!

**Comment by AshKxK** [comment]
Windows color is dark purple and i can see the outline when I alt+Tab but I cannot see the purple when hovering with my mouse.
Tried restarting the explorer.
And I did not add any styles other than the one you told me.

**Comment by AshKxK** [comment]
I do want the keyboard/arrow hover :))

**Comment by bbmaster123** [comment]
then try adding both :) 
I'm sure with the right colors it will look really good!

If its still not working though, lets start looking at things that might be conflicting, mods or otherwise. For example, there are small number of known issues with dual screen setups, do you have 2 or more screens? We can also look at logs, happy to walk you through sharing a log if needed

**Comment by AshKxK** [comment]
I tried adding the other target too, not working.
I do have 2 screens and the Win11 Taskbar Styler. if you need the log lmk

**Comment by bbmaster123** [comment]
could you try dropping down to 1 screen just to confirm if that's where the issue is?
Follow the instructions [here](https://github.com/ramensoftware/windhawk/wiki/Troubleshooting#some-or-all-windhawk-mods-dont-work) to grab a log, hopefully something stands out

**Comment by AshKxK** [comment]
[log.txt](https://github.com/user-attachments/files/18011331/log.txt)

[https://youtu.be/NXbcKYYSKPM](url)

**Comment by bbmaster123** [comment]
ah, okay its my fault, I gave a wrong target and a wrong style, somehow...sorry about that, not sure how that happened!

try this:
```
{
  "theme": "Fluent2Inspired",
  "controlStyles[0].target": "Windows.UI.Xaml.Controls.GridViewItem > Border > Grid > Border",
  "controlStyles[0].styles[0]": "FocusVisualPrimaryThickness=2",
  "controlStyles[0].styles[1]": "FocusVisualPrimaryBrush:=<SolidColorBrush Color=\"{ThemeResource SystemAccentColor}\" Opacity=\".85\"/>",
  "controlStyles[1].target": "Border#ContentBorder@CommonStates > Grid#DroppedFlickerWorkaroundWrapper ",
  "controlStyles[1].styles[0]": "Background@PointerOver=Purple"
}
```

you can just paste that whole code into the mod's advanced tab and hit save. Looks like this on my end, nav on first tile again and mouse hovering over the folder

![image](https://github.com/user-attachments/assets/96166d6a-a1a8-4778-9028-e6ad797db658)

**Comment by AshKxK** [comment]
> {
>   "theme": "Fluent2Inspired",
>   "controlStyles[0].target": "Windows.UI.Xaml.Controls.GridViewItem > Border > Grid > Border",
>   "controlStyles[0].styles[0]": "FocusVisualPrimaryThickness=2",
>   "controlStyles[0].styles[1]": "FocusVisualPrimaryBrush:=<SolidColorBrush Color=\"{ThemeResource SystemAccentColor}\" Opacity=\".85\"/>",
>   "controlStyles[1].target": "Border#ContentBorder@CommonStates > Grid#DroppedFlickerWorkaroundWrapper ",
>   "controlStyles[1].styles[0]": "Background@PointerOver=Purple"
> }

I just change everything that is there or just add, because when I add it says invalid json data

Here is what I have now `{"theme":"Fluent2Inspired","resourceVariables[0].variableKey":"","resourceVariables[0].value":"","controlStyles[0].target":"Windows.UI.Xaml.Controls.GridViewItem","controlStyles[0].styles[0]":"FocusVisualMargin=2","controlStyles[0].styles[1]":"FocusVisualPrimaryBrush:=<SolidColorBrush Color=\"{ThemeResource SystemAccentColor}\" Opacity=\".85\"/>","controlStyles[0].styles[2]":"CornerRadius=8","controlStyles[1].styles[0]":"Background@PointerOver=Purple","controlStyles[1].target":"Border#ContentBorder@CommonStates > Grid#DroppedFlickerWorkaroundWrapper > Border"}`
