### ISSUE TITLE
SidebySide2 swap user and power button 

### ISSUE THREAD

**Issue by JohyanC** [ramensoftware/windows-11-start-menu-styling-guide#124]
Is it possible to swap the location of the user and power buttons, similar to how it is for the standard side by side?

**Comment by SandTechStuff** [comment]
Copy and paste these styles into the advanced mod settings box.

```json
{
	"theme":"SideBySide2",
	"controlStyles[0].target":"StartDocked.NavigationPaneView#NavigationPane",
	"controlStyles[0].styles[0]":"FlowDirection=0",
	"controlStyles[1].target":"Windows.UI.Xaml.Controls.FlyoutPresenter",
	"controlStyles[1].styles[0]":"Margin=0,0,0,0"
}
```

![image](https://github.com/user-attachments/assets/8966d861-518e-4810-876c-e19c7115d1e4)

**Comment by JohyanC** [comment]
Yes. This works perfect. Thank you.
