### ISSUE TITLE
SideBySide without Recommended section

### ISSUE THREAD

**Issue by sebtech33** [ramensoftware/windows-11-start-menu-styling-guide#129]
Mod Author: @m417z 

Hello,
I've been using the "NoRecommendedSection" theme in Windows 11 Start Menu Styler for a long while now.
I actually like the style of "SideBySide" more, but i cant stand the Recommended section as i never used it myself (no hate to those who like it), but is there a possibility for a "SideBySide-NoRecommended" or something like that?

Thank you for all you work i really like Windhawk and your mods,
Sebastian

**Comment by sebtech33** [comment]
Thank you so much your a godsend!
Worked like a charm, thank you!

**Comment by sebtech33** [comment]
Sorry to bother you again and open the thread right after i closed it, but I didn't notice it right away. There seems to be a problem with the alphabet not showing on the right and the inward arrows are in a weird placement. Is there something that can be done about that?

**Comment by m417z** [comment]
Please open a new issue and include screenshots to show what you mean.

**Comment by sebtech33** [comment]
ok, was about to add the screenshots i took since i didn't include them, but ill open a new issue
