### ISSUE TITLE
Issues with Start Menu After Applying and Removing Themes in Windhawk

### ISSUE THREAD

**Issue by AlcanderYoung** [ramensoftware/windows-11-start-menu-styling-guide#13]
After applying a specific theme in Windhawk, my start menu appeared as shown in the screenshot. 
![屏幕截图 2024-05-01 001155](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/104055520/f4e81e98-30a7-4190-8f3e-53e2bb926e73)
Subsequently, I removed the content I had pasted in the advanced settings and attempted to apply other themes. Despite this, my start menu now shows persistent visual artifacts and layout issues as depicted in the second screenshot. 
![Screenshot 2024-05-01 002412](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/104055520/a5e2bfc8-0b56-4bef-a514-59503fb236e8)
![Screenshot 2024-05-01 002719](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/104055520/1b5cf82a-0c5c-4aa2-be84-382cb363085e)

Here are the issues I've noticed:
• The visual effect from the initial theme persists across all themes.
• Text in the start menu is not fully displayed.
• The buttons below are displayed incorrectly.

These issues have not been resolved even after deleting the theme mod. Could you please help investigate whether there is a residual configuration causing this, and how I might fully reset or correct the start menu display?

**Comment by m417z** [comment]
I wasn't able to reproduce the problem with the steps you provided, but I suspect that the recent update to version 1.1.2 might have fixed this. If you can try it with the new version, that would be great.
The changes aren't permanent. After disabling or removing the mod, even if something goes wrong, you can always reset the styles by terminating the start menu process, `StartMenuExperienceHost.exe`. It will be restarted automatically. Alternatively, just log out or restart the computer.

**Comment by AlcanderYoung** [comment]
> 我无法使用您提供的步骤重现该问题，但我怀疑最近对版本 1.1.2 的更新可能已经解决了这个问题。如果您可以使用新版本尝试它，那就太好了。这些更改不是永久性的。禁用或删除模组后，即使出现问题，您也可以随时通过终止开始菜单进程来重置样式。它将自动重新启动。或者，只需注销或重新启动计算机即可。`StartMenuExperienceHost.exe`

The issue has been completely resolved after updating to version 1.1.2. Thank you for the update!
