### ISSUE TITLE
'TranslucentStratMenu': the border of the start menu search is still grey

### ISSUE THREAD

**Issue by SUBearH** [ramensoftware/windows-11-start-menu-styling-guide#136]
The Start menu(expected)-->
![image](https://github.com/user-attachments/assets/fc7092c4-e56d-4a59-999f-cb60302522db)
The Sreach menu(now)-->
![image](https://github.com/user-attachments/assets/2db2cafe-4c9e-41b1-bbca-06aa7bef30a2)

**Comment by m417z** [comment]
Tagging the theme author: @Undisputed00x.

**Comment by SUBearH** [comment]
![image](https://github.com/user-attachments/assets/ebe233b8-2bce-4a2f-b549-81a2af5b45a5)

**Comment by SUBearH** [comment]
It doesn't work. The latest version did not fix this issue
![image](https://github.com/user-attachments/assets/f28cfd88-2ef8-45d1-acd0-2416eda77433)

**Comment by SUBearH** [comment]
it does not work
![image](https://github.com/user-attachments/assets/48d378b7-3822-4157-a179-12f28e41308e)

**Comment by SUBearH** [comment]
before:
![image](https://github.com/user-attachments/assets/8376ec29-78bd-4f43-804d-9f07e99f3e7f)
after:
![image](https://github.com/user-attachments/assets/d6b98cd2-d47d-466e-9e4b-3edcddaf517f)

**Comment by SUBearH** [comment]
Even if I disable all the mods, the Start menu and Search menu still behave differently. This is clearly a Microsoft problem.
![image](https://github.com/user-attachments/assets/092cc895-d35a-4a0b-8164-1224f48e962e)
![image](https://github.com/user-attachments/assets/f5cfb8b5-7cad-41b2-9cbc-2ef538e6dcc2)

**Comment by Undisputed00x** [comment]
> it does not work
> ![image](https://github.com/user-attachments/assets/48d378b7-3822-4157-a179-12f28e41308e)
>

Judging by your picture the border of the Search menu actually has been removed. It seems that your confusing the drop shadow with the border of the menu
