### ISSUE TITLE
Is it supposed to be transparent?

### ISSUE THREAD

**Issue by ItsmcFox** [ramensoftware/windows-11-start-menu-styling-guide#22]
The `TranslucentStartMenu` theme sometimes makes the start menu completely transparent after like a couple hours after it is applied. This has happened multiple times and I don't like it doing that. Is there a way fix this?

**Comment by m417z** [comment]
It's either a problem with the theme, or a problem with the mod. @Undisputed00x any idea?
If you find a way to reproduce the problem, let me know. Without a way to reproduce it, it's difficult to understand what causes the problem.

**Comment by ItsmcFox** [comment]
I pasted the code for a SideBySide in the box for manually doing it. And set the theme is the settings tab with the drop down menu at the top to TranslucentStartMenu and after a while it messed up like that. I don’t know if it is a problem with the mod or the theme but I’m guessing it’s the theme because it only happens with that theme.

**Comment by Undisputed00x** [comment]
@ItsmcFox Couldn't reproduce the issue on my part. I've follow your steps and the theme works as it should. I will keep this configuration for some time but its unlikely that a problem will occur
<details><summary>Example</summary>
<p>


![Screenshot 2024-06-07 140806](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/80290008/236bf8d0-ec6d-47b4-9daa-8cc374527c6d)


</p>
</details> 




> The `TranslucentStartMenu` theme sometimes makes the start menu completely transparent after like a couple hours after it is applied. 

Does this issue happens after when/if your system gets into power saving mode ?

**Comment by Undisputed00x** [comment]
@ItsmcFox Power saving mode naturally its turned on when the battery level is below a certain level. 

You can find lots of guide how to handle power saving on your system here an example: https://www.wisecleaner.com/think-tank/562-How-to-Enable-or-Disable-Battery-Saver-on-Windows-11.html

**Comment by ItsmcFox** [comment]
I don’t want to disable it I just want it to not do that when it is enabled

**Comment by Undisputed00x** [comment]
Power saving mode disables windows effects by default and you cant change that. Normally doesn't make sense to keep effects on when your system tries to save power, because the windows effects like translucency consume lots of it. 
What you can do is to configure the windows power plan like mentioned before.

**Comment by ItsmcFox** [comment]
Its okay now I dont want to change my settings for the battery saver.
