### ISSUE TITLE
How do I remove the border from the start menu panel?

### ISSUE THREAD

**Issue by bagarwa** [ramensoftware/windows-11-start-menu-styling-guide#26]
I wanted my start menu theme to be a combination of [TranslucentStartMenu](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/TranslucentStartMenu/README.md) and [SideBySide](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/SideBySide/README.md) and [NoRecommendedSection](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/NoRecommendedSection/README.md). 

So, I selected SideBySide as my starting theme, and then added some control styles to it. This is my Mod settings - 
```
{"theme":"SideBySide","controlStyles[0].target":"Border#AcrylicBorder","controlStyles[0].styles[0]":"Background:=<AcrylicBrush BackgroundSource=\"Backdrop\" TintColor=\"Black\" TintOpacity=\"0.25\" />","resourceVariables[0].variableKey":"","resourceVariables[0].value":"","controlStyles[1].target":"Windows.UI.Xaml.Controls.Grid#ShowMoreSuggestions, Windows.UI.Xaml.Controls.Grid#SuggestionsParentContainer, Windows.UI.Xaml.Controls.Grid#TopLevelSuggestionsListHeader","controlStyles[1].styles[0]":"Visibility=Collapsed","controlStyles[2].target":"StartMenu.PinnedList","controlStyles[2].styles[0]":"Height=504"}
``` 

I have three nitpicky issues with how it is looking now - 
1. The entire start menu panel now has a 1 (2?) pixel white border some times. How do I remove that?
2. The start menu panel is always grey colored, and not picking up the wallpaper or background color. If I remove the TintColor=\"Black\" part from the settings, then the white color border issue gets solved, but the start menu panel then becomes very light grey colored instead, and still doesn't pick up wallpaper color. 
3. And this mod doesn't affect the search panel at all, so switching from start menu panel to the search panel is a little jarring. 

# Example Screenshots
![start](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/4424058/a0802016-509e-48ef-81dc-ee9ff08179b9)

![Search](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/4424058/4f64d02e-6cca-40c8-b533-fdacb48586b5)

**Comment by Undisputed00x** [comment]
TranslucentStartMenu has already no recommended section, all you need to do is to select one of the themes you'd like and follow the manual installation guide from the second theme you like to combine.

**Comment by bagarwa** [comment]
GREAT!! Earlier I had only read the readme at the root. I hadn't seen that each of the themes have their own sub-folder and their own readme too (though I linked to them in my post!! I feel like a dum-dum now. 🙃). (In my defense, I had simply copy-pasted those theme names from homepage.)

I've now started with TranslucentStartMenu theme and then added the code content of SideBySide in advance settings. Start Panel now looks awesome. 

Can this same theme be applied to the search panel though? (Maybe in next version of this mod?)

**Comment by m417z** [comment]
> Can this same theme be applied to the search panel though? (Maybe in next version of this mod?)

Some styles can be applied to the search panel. See this paragraph:
https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/TranslucentStartMenu/README.md#translucentsearchmenu-support

**Comment by bagarwa** [comment]
> Some styles can be applied to the search panel. See this paragraph: https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/TranslucentStartMenu/README.md#translucentsearchmenu-support

That didn't work. At first I tried to combine my existing code with the code from [TranslucentSearchMenu Support section](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/TranslucentStartMenu/README.md#translucentsearchmenu-support), like this - 
<details>
<summary>For TranslucentStartMenu + SideBySide + TranslucentSearchMenu</summary>

```json
{
  "controlStyles[0].target": "Windows.UI.Xaml.Controls.Grid#UndockedRoot",
  "controlStyles[0].styles[0]": "Visibility=Visible",
  "controlStyles[0].styles[1]": "MaxWidth=700",
  "controlStyles[0].styles[2]": "Margin=0,0,300,0",
  "controlStyles[1].target": "Windows.UI.Xaml.Controls.Grid#AllAppsRoot",
  "controlStyles[1].styles[0]": "Visibility=Visible",
  "controlStyles[1].styles[1]": "Width=350",
  "controlStyles[1].styles[2]": "Transform3D:=<CompositeTransform3D TranslateX=\"-602\" />",
  "controlStyles[2].target": "StartDocked.AllAppsGridListView > ScrollViewer > Border > Grid > ScrollContentPresenter > ItemsPresenter > TileGrid",
  "controlStyles[2].styles[0]": "Transform3D:=<CompositeTransform3D TranslateX=\"20\" />",
  "controlStyles[3].target": "Grid#AllAppsPaneHeader",
  "controlStyles[3].styles[0]": "Transform3D:=<CompositeTransform3D TranslateX=\"20\" />",
  "controlStyles[4].target": "Windows.UI.Xaml.Controls.Button#CloseAllAppsButton",
  "controlStyles[4].styles[0]": "Visibility=Collapsed",
  "controlStyles[5].target": "StartDocked.StartSizingFrame",
  "controlStyles[5].styles[0]": "MinWidth=850",
  "controlStyles[5].styles[1]": "MaxWidth=850",
  "controlStyles[6].target": "Windows.UI.Xaml.Controls.Grid#ShowMoreSuggestions",
  "controlStyles[6].styles[0]": "Visibility=Collapsed",
  "controlStyles[7].target": "Windows.UI.Xaml.Controls.Button#ShowAllAppsButton",
  "controlStyles[7].styles[0]": "Visibility=Collapsed",
  "controlStyles[8].target": "Windows.UI.Xaml.Controls.ContentControl",
  "controlStyles[8].styles[0]": "Transform3D:=<CompositeTransform3D TranslateX=\"-200\" />",
  "controlStyles[9].target": "Windows.UI.Xaml.Controls.GridView#RecommendedList > Windows.UI.Xaml.Controls.Border > Windows.UI.Xaml.Controls.ScrollViewer#ScrollViewer > Windows.UI.Xaml.Controls.Border#Root > Windows.UI.Xaml.Controls.Grid > Windows.UI.Xaml.Controls.ScrollContentPresenter#ScrollContentPresenter > Windows.UI.Xaml.Controls.ItemsPresenter > Windows.UI.Xaml.Controls.ItemsWrapGrid > Windows.UI.Xaml.Controls.GridViewItem",
  "controlStyles[9].styles[0]": "MaxWidth=220",
  "controlStyles[9].styles[1]": "MinWidth=100", 
  "controlStyles[10].target": "Border#AcrylicBorder",
  "controlStyles[10].styles[0]": "CornerRadius=15",
  "controlStyles[10].styles[1]": "Background:=<AcrylicBrush TintColor=\"Transparent\" TintLuminosityOpacity=\"0\" TintOpacity=\"0\" Opacity=\"1\"/>",
  "controlStyles[10].styles[2]": "BorderThickness=0,0,0,0",
  "controlStyles[11].target": "Border#AcrylicOverlay",
  "controlStyles[11].styles[0]": "Visibility=Collapsed",
  "controlStyles[12].target": "Border#BorderElement",
  "controlStyles[12].styles[0]": "CornerRadius=10",
  "controlStyles[12].styles[1]": "BorderThickness=0,0,0,0",
  "controlStyles[12].styles[2]": "Background:=<AcrylicBrush TintLuminosityOpacity=\"0.03\" TintOpacity=\"0\" Opacity=\"1\"/>",
  "controlStyles[13].target": "Grid#ShowMoreSuggestions",
  "controlStyles[13].styles[0]": "Visibility=Collapsed",
  "controlStyles[14].target": "Grid#SuggestionsParentContainer",
  "controlStyles[14].styles[0]": "Visibility=Collapsed",
  "controlStyles[15].target": "Grid#TopLevelSuggestionsListHeader",
  "controlStyles[15].styles[0]": "Visibility=Collapsed",
  "controlStyles[16].target": "StartMenu.PinnedList",
  "controlStyles[16].styles[0]": "Height=504",
  "controlStyles[17].target": "MenuFlyoutPresenter",
  "controlStyles[17].styles[0]": "Background:=<AcrylicBrush TintColor=\"Transparent\" TintLuminosityOpacity=\"0\" TintOpacity=\"0\" Opacity=\"1\"/>",
  "controlStyles[17].styles[1]": "BorderThickness=0,0,0,0",
  "controlStyles[18].target": "Border#AppBorder",
  "controlStyles[18].styles[0]": "Background:=<AcrylicBrush TintColor=\"Transparent\" TintLuminosityOpacity=\"0\" TintOpacity=\"0\" Opacity=\"1\"/>",
  "controlStyles[18].styles[1]": "BorderThickness=0,0,0,0",
  "controlStyles[19].target": "Border#LayerBorder",
  "controlStyles[19].styles[0]": "Visibility=Collapsed",
  "controlStyles[20].target": "Border#TaskbarSearchBackground",
  "controlStyles[20].styles[0]": "Background:=<AcrylicBrush TintColor=\"Transparent\" TintLuminosityOpacity=\"0.03\" TintOpacity=\"0\" Opacity=\"1\"/>",
  "controlStyles[20].styles[1]": "CornerRadius=10",
  "controlStyles[20].styles[2]": "BorderThickness=0,0,0,0"
}
```
</details>

When that didn't work, I replaced the entire code in Mod settings section with the with the code from [TranslucentSearchMenu Support section](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/TranslucentStartMenu/README.md#translucentsearchmenu-support).

Here's my advanced section - 
![Search](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/4424058/1e6bc1b7-63fe-45c5-ab70-b62071ff898f)

Search panel still stays the stock styled. 
Moreover, when I tried to manually run SearchHost.exe via win+R, that throws this error - 
> Windows cannot find 'SearchHost.exe'. Make sure you typed the name correctly, and then try again.

I searched for SearchHost.exe in Everything and that gives this result - 
![Everything](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/4424058/de9e67ac-0dc9-4296-a73a-28b8ce79a373)
I also restarted the Explorer process, in case it was dependent on that. No dice. 

Did I go wrong somewhere?

**Comment by m417z** [comment]
> When that didn't work, I replaced the entire code in Mod settings section with the with the code from [TranslucentSearchMenu Support section](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/TranslucentStartMenu/README.md#translucentsearchmenu-support).

That should work. @Undisputed00x any idea?

**Comment by Undisputed00x** [comment]
@bagarwa If you disable accent colors on startmenu and taskbar through the Settings do you see the problem to persist?

**Comment by bagarwa** [comment]
> @bagarwa If you disable accent colors on startmenu and taskbar through the Settings do you see the problem to persist?

~~Yes, even when I disable "Show accent color on Start and taskbar" from Windows settings, this problem still persists.~~
Ahh... restarting the Explorer process after disabling the above setting worked.  

Thanks for the quick responses. Absolutely love this mod. ❤️🤜🤛
