### ISSUE TITLE
Acrylic background in Battery Saver/Energy Saver

### ISSUE THREAD

**Issue by MuscularPuky** [ramensoftware/windows-11-start-menu-styling-guide#29]
Since Windows 10, during Battery Saver/Energy Saver enables, all acrylic/mica effect disabled and filled accent color instead. however when we hook the acrylic material manually, the acrylic background is become transparent but accent color does not fill. Can we handle athis case? ofc someone loves transparent background effect but not to me as it makes the contents unreadable.

**Comment by MuscularPuky** [comment]
I did it
we can use `FallbackColor` parameter

**Comment by m417z** [comment]
@Undisputed00x IMO worth adding it to your Translucent mods.

**Comment by Undisputed00x** [comment]
@m417z @MuscularPuky so if i understood correctly, i need to add the FallbackColor"#" with the rest of the AcrylicBrush attributes ?

**Comment by m417z** [comment]
As far as I understand, yes, but it's best to just try it with your Translucent themes.

**Comment by MuscularPuky** [comment]
ah I just forgot to mention it Windows default fallback color is `{ThemeResource SystemAccentColorLight1}` and `{ThemeResource SystemAccentColorDark1}` so we can remove "Light/Dark#" or adjust # to between 1~3. text color is reversed (e.g. BG Light2-TXT Dark1, BG Light1-TXT Dark2, BG none-TXT Light/Dark3)
