### ISSUE TITLE
Change Start Menu background color

### ISSUE THREAD

**Issue by B1ue-Dev** [ramensoftware/windows-11-start-menu-styling-guide#3]
I haven't figured out what key to change, despite having dig into UWPSpy. Any help would be greatly appreciated.

**Comment by vmsz** [comment]
Target: Windows.UI.Xaml.Controls.Border#AcrylicBorder
Style: Background:=<SolidColorBrush Color="#HexColor" />

Just replace the Color attribute with any hex color

**Comment by vmsz** [comment]
Target: `Windows.UI.Xaml.Controls.Border#AcrylicBorder`

Style: `Background:=<SolidColorBrush Color="#HexColor" />`

Just replace the Color attribute with any hex color.

**Comment by ItsmcFox** [comment]
Hi, B1ue-Dev it seems like this issue has been **resolved** , so it would be most helpful to mark this issue as completed, for now.
