### ISSUE TITLE
Move start menu to top of the screen

### ISSUE THREAD

**Issue by flysqu** [ramensoftware/windows-11-start-menu-styling-guide#40]
Hi im using the vertical start menu but this doesn't change the position of the start menu
![image](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/assets/98214547/e98ce12e-f790-4ddc-b0dc-a9f3470609ff)
I cant quite understand how the css works for this haha :3

**Comment by bbmaster123** [comment]
You should be able to move the menu around in Start Menu Styler like this:
```
Target: 
Windows.UI.Xaml.Controls.Grid#UndockedRoot
Style: 
Margin=0,-20,0,0
```
That's left, top, right, bottom, in that order. You can use positive or negative numbers.
Increase or decrease to move the menu around. The amount you need to move the menu likely depends on your resolution.

post back here if you need any clarification :)

**Comment by flysqu** [comment]
Thanks!!! forgot to close this haha
