### ISSUE TITLE
[Windows 11 Start Menu Styler] Account menu broke after Windows 11 Build 22631.3880

### ISSUE THREAD

**Issue by bagarwa** [ramensoftware/windows-11-start-menu-styling-guide#41]
@m417z 

With today's update Tuesday, Windows 11 Build 22631.3880, Windows Start Menu changed the account manager page. 
[[article with details](https://www.windowslatest.com/2024/07/09/windows-11-kb5040442-out-with-features-direct-download-msu/#:~:text=Start%20menu%20gets%20account%20manager)]

It now looks like this - 
![stock](https://github.com/ramensoftware/windhawk-mods/assets/4424058/6deb5931-b214-4a5f-8632-742e918c0200)

But with the mod enabled, it looks like this - 
![modded](https://github.com/ramensoftware/windhawk-mods/assets/4424058/c796041a-fef8-4fb0-8436-00ad9653bbfd)

I guess the mod needs some changes to accommodate this new change in the start menu. 

(I know this update just landed. So, this "bug report" is not a complaint. 😛 Posting it just to report it.)

**Comment by bbmaster123** [comment]
hey,
sorry for the delay, I had to update windows before I was able to reproduce the issue, I still had the old menu
Please give this code a try and let me know if anything is cut off or missing:
`{
  "theme": "",
  "controlStyles[0].target": "Grid#UndockedRoot",
  "resourceVariables[0].variableKey": "",
  "resourceVariables[0].value": "",
  "controlStyles[0].styles[0]": "MaxWidth=700",
  "controlStyles[0].styles[1]": "Margin=0,0,300,0",
  "controlStyles[1].target": "Grid#AllAppsRoot",
  "controlStyles[1].styles[0]": "Visibility=Visible",
  "controlStyles[1].styles[1]": "Width=390",
  "controlStyles[1].styles[2]": "Margin=-590,0,590,0",
  "controlStyles[2].target": "Windows.UI.Xaml.Controls.Button#CloseAllAppsButton",
  "controlStyles[2].styles[0]": "Visibility=Collapsed",
  "controlStyles[3].target": "StartDocked.StartSizingFrame",
  "controlStyles[4].target": "Windows.UI.Xaml.Controls.Button#ShowAllAppsButton",
  "controlStyles[4].styles[0]": "Visibility=Collapsed",
  "controlStyles[5].target": "Windows.UI.Xaml.Controls.ContentControl[2]",
  "controlStyles[5].styles[0]": "Transform3D:=<CompositeTransform3D TranslateX=\"-32\" TranslateY=\"25\"/>",
  "controlStyles[6].target": "Windows.UI.Xaml.Controls.TextBlock#PinnedListHeaderText",
  "controlStyles[6].styles[0]": "Transform3D:=<CompositeTransform3D TranslateX=\"-22\" />",
  "controlStyles[7].target": "Grid#TopLevelSuggestionsListHeader",
  "controlStyles[7].styles[0]": "Transform3D:=<CompositeTransform3D TranslateX=\"-25\" TranslateY=\"25\"  />",
  "controlStyles[8].target": "Windows.UI.Xaml.Controls.Primitives.ScrollBar[3]",
  "controlStyles[8].styles[0]": "Margin=0,0,40,0",
  "controlStyles[9].target": "Windows.UI.Xaml.Controls.Primitives.ScrollBar[1]",
  "controlStyles[9].styles[0]": "Margin=0,0,38,0",
  "controlStyles[10].target": "Microsoft.UI.Xaml.Controls.PipsPager#PinnedListPipsPager",
  "controlStyles[10].styles[0]": "Margin=-8,0,8,0",
  "controlStyles[3].styles[0]": "MaxWidth=860",
  "controlStyles[11].target": "Windows.UI.Xaml.Controls.ItemsWrapGrid > Windows.UI.Xaml.Controls.GridViewItem",
  "controlStyles[11].styles[0]": "MaxWidth=220",
  "controlStyles[11].styles[1]": "MinWidth=85",
  "controlStyles[11].styles[2]": "MaxHeight=120",
  "controlStyles[12].target": "StartMenu.PinnedList#StartMenuPinnedList",
  "controlStyles[12].styles[0]": "Margin=-15,0,5,0",
  "controlStyles[13].target": "Grid#ShowMoreSuggestions",
  "controlStyles[13].styles[0]": "Margin=0,20,0,-20",
  "controlStyles[14].target": "Grid#MoreSuggestionsRoot",
  "controlStyles[14].styles[0]": "Margin=0,-26,-33,0",
  "controlStyles[14].styles[1]": "Width=625"
}`

**Comment by bagarwa** [comment]
Great! That worked.

**Comment by m417z** [comment]
Fixed in Windows 11 Start Menu Styler v1.1.5.
