### ISSUE TITLE
Customizing the level of transparency

### ISSUE THREAD

**Issue by EmanDev** [ramensoftware/windows-11-start-menu-styling-guide#47]
Details:
Theme: TransluscentStartMenu
Control Styles included: Search bar from start menu removed

Issue: How do you customize the level of transparency of the start menu?
Issue 2: Is it possible to remove this shadow or line when start menu is active?

![image](https://github.com/user-attachments/assets/c3f005d7-bbe6-4840-a2dc-e6931a80b0c0)

**Comment by bbmaster123** [comment]
Hi Eman, I like guitars and computers too!

1. to alter transparency, put the element you want to style in the target box. you can get this from UWPSpy, or from the guide that I hope you've had a chance to see: https://github.com/ramensoftware/windows-11-start-menu-styling-guide
Then to actually control the transparency, you can use an 8 character RGBA hex code 
ex
`Background=#BB445566`

you can also use the color name Transparent, or you can use a an AcrylicBrush, which is the style being applied in this theme ex 
`Background:=<AcrylicBrush TintColor="Red" TintOpacity="0.8" />`
Note the colon before the = when using a brush.

2. Yes, as in 1 you first need the target of the shadow, in this case it is Border#DropShadow, and set a style that will hide it, for ex
```
Opacity=0
Visibility=Collaped
```
either of those will work. Or you can do something else with the shadow if you like, maybe change its color or position etc

I hope this helps, let me know if you need any more info! :)

**Comment by EmanDev** [comment]
@bbmaster123 

Thank you for your help! Closing this issue now since you've given all the info I need.
