### ISSUE TITLE
Windows11_Metro10 - ui bugs

### ISSUE THREAD

**Issue by kamez104** [ramensoftware/windows-11-start-menu-styling-guide#60]
- the items under "Recommended" aren't aligned properly, even when the language is set to en-us
- can't exit semantic search by clicking the button again; you have to reopen the start menu
- context menu labels are shifted to the right
![obraz](https://github.com/user-attachments/assets/300882c0-476b-42ed-aeea-0a80a375a20e)
![obraz](https://github.com/user-attachments/assets/2cba5ba3-8ad1-4f49-8b44-f2b2a51c149a)

**Comment by bbmaster123** [comment]
thanks, fixed!
semantic zoom button can't be enabled on the zoomed out view. Its only a zoom out button, not a zoom toggle, unfortunately, nothing I can do. You can click any of the letters to return to the app list though
