### ISSUE TITLE
Search menu style

### ISSUE THREAD

**Issue by markox92** [ramensoftware/windows-11-start-menu-styling-guide#69]
I have done with start menu

![Screenshot 2024-08-27 015251](https://github.com/user-attachments/assets/f84634b7-76af-4751-ab65-b7d4f5fa8035)

I want to style the search menu to have the same design; is it possible to do that? If yes, can anyone explain how?

![Screenshot 2024-08-27 015820](https://github.com/user-attachments/assets/971a4671-b426-4722-aca8-55c816d6d3c2)

**Comment by bbmaster123** [comment]
add SearchHost.exe to your include list in advanced
Then use uwpspy to find the search menu targets for whatever else is remaining

Unfortunately you can't style anything in the webview element

**Comment by markox92** [comment]
Done, Thanks.

![Screenshot 2024-08-27 045524](https://github.com/user-attachments/assets/525bd1d8-4a2c-48bb-93cb-78bd450676a1)

**Comment by 88neil** [comment]
> I have done with start menu
> 
> ![Screenshot 2024-08-27 015251](https://github.com/user-attachments/assets/f84634b7-76af-4751-ab65-b7d4f5fa8035)
> 
> I want to style the search menu to have the same design; is it possible to do that? If yes, can anyone explain how?
> 
> ![Screenshot 2024-08-27 015820](https://github.com/user-attachments/assets/971a4671-b426-4722-aca8-55c816d6d3c2)

I really like your taskbar style. Could you share how you achieved this look?
