### ISSUE TITLE
Is there any way I can add the logout button to the "SideBySideMinimal" menu?

### ISSUE THREAD

**Issue by THEBOSSES7000** [ramensoftware/windows-11-start-menu-styling-guide#70]
I love this version of the menu, the only problem I have is that I have multiple users and when one of my family members wants to use the computer I have to restart the computer or use "Alt+F4" on the desktop to log out.

**Comment by bbmaster123** [comment]
Good point, Microsoft moving the log out button from the power menu to the user menu means makes that option unavailable in SBSminimal.

I've got two options for you, just pick whichever works better for you:

1. right click start menu > shutdown or sign out > sign out

2. or add this style in windhawk:
 ```
  Target: StartDocked.UserTileView
  Style: Visibility=Visible
```

**Comment by THEBOSSES7000** [comment]
Thanks, i added the style in Windhawk and it worked perfectly, thanks.

**Comment by THEBOSSES7000** [comment]
Thanks, i added the style in Windhawk and it worked perfectly, thanks.
