### ISSUE TITLE
[Start menu padding require to fix] ver 24h2 build 26100.1742 ghost spectre win 11

### ISSUE THREAD

**Issue by hafidzahm** [ramensoftware/windows-11-start-menu-styling-guide#82]
![bug](https://github.com/user-attachments/assets/5cd520e4-26cd-4fd2-b026-8815639edfe9)

**Comment by m417z** [comment]
Which theme are you using? Not all themes are compatible with Windows 11 version 24H2 yet.

**Comment by hafidzahm** [comment]
ok thanks for the information, i using theme in picture below, i didnt know the name of theme is
![Uploading bugg.png…]()

**Comment by m417z** [comment]
Looks like you're using the start menu from here: https://www.vinstartheme.com/windows-11x-start-menu/
Perhaps it doesn't support Windows 11 version 24H2 properly. It's best to contact their authors about it.
@vinstartheme FYI.

**Comment by hafidzahm** [comment]
oke, sorry for misunderstanding.....
