### ISSUE TITLE
Where can I check all the possible styling options we have?

### ISSUE THREAD

**Issue by bergamin** [ramensoftware/windows-11-start-menu-styling-guide#84]
The [style guide](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/README.md) has a few examples, but there are some things I want to use that are not listed there. The most obvious one that we have in the pre-defined themes, but isn't listed, is the All Apps list.

None of the pre-defined themes have what I want, which is basically the No Recommendations theme with the All Apps list to the side. The closest one is Side By Side Minimal, but I want to keep the Search and Account button.

**Comment by m417z** [comment]
It's difficult to make a comprehensive list, and surely impossible to list all styling options, just like it's not possible to list all possible programs for a programming language.
Since the Side By Side Minimal theme is the closest to your ideal theme, you can import it manually and play with the styles, unhiding and repositioning the elements you want back.

**Comment by bergamin** [comment]
I can see where you are coming from. I tried looking for it in the docs based on the ones that are listed, but it seems MS didn't organize these controls comprehensively. You would have to already know them by experience

That being said, we could have a list at least with the components that we usually associate with the start menu, like the apps list and an explanation of how to put things in places.

About changing a pre-defined theme, I didn't know it was possible to override them. I'll try it out. Thanks!

**Comment by m417z** [comment]
> it seems MS didn't organize these controls comprehensively

Most things are documented, but it takes some experience to navigate through the docs. Usually looking up the name of the style/control together with "UWP" gets you to the right place.

> we could have a list at least with the components that we usually associate with the start menu

Certainly! Contributions are welcome :)

> About changing a pre-defined theme, I didn't know it was possible to override them. I'll try it out. Thanks!

Yeah, look at the "Manual installation" section [on the theme page](https://github.com/ramensoftware/windows-11-start-menu-styling-guide/blob/main/Themes/SideBySideMinimal/README.md#manual-installation), it will result in the theme styles being imported to the mod settings, at which point you can start editing them.
