### ISSUE TITLE
SideBySideMinimal Inverted

### ISSUE THREAD

**Issue by Bribbo38** [ramensoftware/windows-11-start-menu-styling-guide#91]
Hi I'm new to this software and I really like the SideBySideMinimal Theme, but I would like to be in the same order as the normal SideBySide: with the apps on the right and the pinned on the left.
If anyone can help me or find some kind of software that let's you preview or test so I can learn more how to customize. I would really appreciate it.
Thanks for the help

**Comment by bbmaster123** [comment]
man I really gotta finish this guide up!
please keep in mind its not 100% done, but it should still help a lot, I'd think :)
[howto](https://github.com/bbmaster123/FWFU/blob/main/uwpspy.md)

let me know if anything requires further explanation, cheers!

**Comment by Bribbo38** [comment]
Thank you very much, I'm gonna look more in to it when I can. II think it's easy to understand, but I need to try before say it for sure.

**Comment by Bribbo38** [comment]
Hi I tried to modify the Start menu but some times it just stop working and it reload the explorer.exe program. I also can't get to the actual Start menu. I can just select the System tray and bar but not the menu that appears when clicking the Windows logo.
Since the software is not selected when pressing *win* I also can't use the CTRL+D method

**Comment by bbmaster123** [comment]
@Bribbo38 
okay I'll be more clear about that in the guide. 
The issue is that you need to select the process where you'd like to target, so for taskbar thats explorer.exe, for start, that's startmenuexperiencehost.exe
uwpspy should come up when the start menu is open and dissapear when you dismiss it

**Comment by Bribbo38** [comment]
Okay, thank you. I'm gonna try with that process instead and test if everything work.

**Comment by Bribbo38** [comment]
I managed to get a better result than with the stocks one, thank you for your help and the guide.

![Screenshot 2024-10-12 230732](https://github.com/user-attachments/assets/37f70372-d090-4318-ba6e-cf4158a319c5)
